name: oftal_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  email_validator: ^3.0.0
  fluro: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  go_router: ^16.1.0
  google_fonts: ^6.3.0
  riverpod_annotation: ^2.6.1
  shadcn_ui: ^0.28.5
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
